### ISSUE TITLE
程式撰寫

### ISSUE THREAD

**Issue by creatopgrace** [creatop/grand-view#6]
## @NineWei  昇財麗禧程式撰寫下周(7/11)排入
**slide的部分**
1.首頁輪播圖
2.//相片簿
客房 01_room / room_photo_01.php
餐聽及會議 02_restaurant / restaurant_photo.php
周邊景點 04_attractions / attractions_photo.php

3.//deatil頁面 
客房 01_room / room_detail.php  
餐聽及會議 02_restaurant/restaurant_detail.php
促銷活動 03_special/special_overview.php
周邊景點 04_attractions/attractions_detail.php

## 程式串接
![image](https://cloud.githubusercontent.com/assets/20021057/16644442/9c5115b8-444f-11e6-8524-e9c691ea265b.png)
有相片簿的要串到每一頁的detail slide
![image](https://cloud.githubusercontent.com/assets/20021057/16644475/ed0daeb2-444f-11e6-918e-74045850b9df.png)
![image](https://cloud.githubusercontent.com/assets/20021057/16644483/fa9911c0-444f-11e6-8b49-c91c57a4de5a.png)

**Comment by NineWei** [comment]
slide的部分
1.首頁輪播圖   OK
2.//相片簿
客房 01_room / room_photo_01.php
餐聽及會議 02_restaurant / restaurant_photo.php
周邊景點 04_attractions / attractions_photo.php

3.//deatil頁面 
客房 01_room / room_detail.php

餐聽及會議 02_restaurant/restaurant_detail.php
促銷活動 03_special/special_overview.php
周邊景點 04_attractions/attractions_detail.php
